id: hl7.fhir.uv.epi-jp-ig
canonical: http://hl7.org/fhir/uv/epi-jp-ig
name: epi-jp
title: Japanese Electronic Medicinal Product Information (ePI-JP) Implementation Guide
description: FHIR Implementation Guide representing how to create Electronic Medicinal Product Information (ePI) in alignment with Japanese PMDA requirements.
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 5.0.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Gravitate Health Project
  url: https://www.gravitatehealth.eu/
  # email: test@example.org

pages:
  index.md:
      title: Home
  background.md:
      title: Background
  usecases.md:
      title: Use Cases
  epi-components.md:
      title: ePI Components
  mapping.md:
      title: Mapping to ePI
  build-overview.md:
      title: Overview
  gettingstarted.md:
      title: Getting Started
  tech-style-guide.md:
      title: Technical Style Guide
  terminology.md:
      title: Terminology
  downloads.md:
      title: Downloads

menu:
  Home: index.html
  Background: background.html
  Getting Started: gettingstarted.html
  ePI Components: epi-components.html
  Use Cases: usecases.html
  Mapping to ePI: mapping.html
  Overview: build-overview.html
  Technical Style Guide: tech-style-guide.html
  Terminology: terminology.html
  Downloads: downloads.html
  Artifacts: artifacts.html



instanceOptions:
  manualSliceOrdering: true # true | false
